# Generated by Django 5.2.4 on 2025-08-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainer_profile',
            new_name='TrainerProfile',
        ),
    ]
