# Generated by Django 5.2.4 on 2025-07-29 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='gym_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class_type')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trainer_profile')),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('class_type', 'trainer', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='class_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.gym_classes')),
            ],
            options={
                'ordering': ['-reservation_date'],
                'unique_together': {('user', 'gym_class')},
            },
        ),
        migrations.CreateModel(
            name='class_membership_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.membership_plan')),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.gym_classes')),
            ],
            options={
                'ordering': ['gym_class', 'membership_plan'],
                'unique_together': {('gym_class', 'membership_plan')},
            },
        ),
    ]
