# Generated by Django 5.2.4 on 2025-08-04 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('users', '0002_rename_trainer_profile_trainerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymclass',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_classes', to='classes.classtype'),
        ),
        migrations.AlterField(
            model_name='gymclass',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_classes', to='users.trainerprofile'),
        ),
    ]
